### ISSUE TITLE
Redesign FakeScheduler again

### ISSUE THREAD

**Issue by jskeet** [googleapis/gax-dotnet#112]
We need more control over when the clock advances - I believe we essentially want to do it only when the system is "idle" apart from threads waiting on tasks we've returned. I suspect that implementing that will require a custom task scheduler. Far from impossible, but not worth doing right now.

**Comment by chrisdunelm** [comment]
Since PR #210 I'm fairly sure this is as good as `FakeScheduler` can get without a custom task scheduler, and therefore also custom `ConfigureAwait`, as in pubsub. Code [here](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/tree/master/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/Tasks) and [here](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/tree/master/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Tasks).
This pubsub fake scheduler allows much more accurate testing of async code, but does require *all* code to be written without using the standard `Task.*` methods. E.g. can't use `Task.Run(...)`, `Task.WhenAny(...)`, etc... Must use `taskHelper.Run(...)`, `taskHelper.WhenAny(...)`, etc... In non-testing environments these simply delegate to the `Task.` methods; but in testing they use the custom task scheduler.

I think we should probably close this issue, as `FakeScheduler` is mostly good enough.
If it ever isn't, then we should consider making the pubsub taskscheduler available in gax, and using it where required.

**Comment by jskeet** [comment]
SGTM - closing now :)
