### ISSUE TITLE
Extension methods to convert between common protos and .net types

### ISSUE THREAD

**Issue by abe545** [googleapis/gax-dotnet#250]
At namely, we're building grpc services in .net, and one of the pain points we've had is when trying to use common types such as `money` and `date` in the proto. We have to convert them in our code to their native .net types (`decimal` and `DateTime`/`DateTimeOffset`), so a few teams have built their own extension methods to handle these conversions. Instead of reinventing the wheel, we're going to put them in a shared location, and I was thinking this would be the appropriate place.

We'd like to see extension methods to covert `money` <->`decimal`, and `date` <-> `DateTime` and `DateTimeOffset` - is this something you are interested in having in this repo (specifically the `Google.Api.CommonProtos` nuget package)? My org has devs who have already written this code, so we'd be happy to contribute them here if you think it is a good idea.

**Comment by jskeet** [comment]
Going between Date and DateTime definitely makes sense (and we have extension methods in Google.Protobuf for Timestamp already). I'm less immediately convinced about decimal and money, but I think it would mostly be a matter of finding the right names... it's not like it would be converting *all* of the value.

Note that as everything is partial, while the conversions *from* BCL types need to be extension methods, the conversions *to* BCL types can be regular instance methods. (That's one advantage of them being in this repo instead of your own.)

**Comment by abe545** [comment]
Thanks for the feedback, @jskeet. I like the approach of adding to the partial class for converting to the .net types. For the other way around, should we keep it consistent by adding cast operators and/or constructor overloads? Or do you favor extension methods on the .net types?

As for the money - what if we instead added a property to the class (it would be get/set). It would allow us to use the value in the calculations while maintaining that a `decimal` is not the entirety of the money proto.

**Comment by jskeet** [comment]
I wouldn't add an extra constructor. I'd add static factory methods, and then extension methods that just call the factory methods.

For the property on `Money`, do you mean it would add extra state, or just perform the conversions on the fly? The latter sounds reasonable to me.

**Comment by abe545** [comment]
Sounds good. 

I meant it would do conversions on the fly.

**Comment by jskeet** [comment]
Closing as this is now implemented.

**Comment by jskeet** [comment]
This has now been released via Google.Api.CommonProtos version 1.3.0.

(It may take a little while to be validated and indexed.)
