### ISSUE TITLE
Support Stackdriver Kubernetes Engine Monitoring

### ISSUE THREAD

**Issue by jskeet** [googleapis/gax-dotnet#347]
Currently we create monitored resource types of either "container" or "gke_container" (pre/post #346).
Those are for *legacy* Stackdriver; to support Stackdriver Kubernetes Engine Monitoring we need to use "k8s_container" instead.

Unfortunately it's hard to detect whether a cluster uses legacy or new-style Stackdriver. We can do it if we have access to the GKE API, but that typically won't be the case.

**Comment by jskeet** [comment]
We should look at this again before 3.0, in case we want to change the default.

**Comment by garethbudden** [comment]
Out of interest why is the GKE api not typically available?  For now I've managed to create the correct set of labels for legacy vs new stackdriver logging by hacking around with the metadata json file (happy to share the horror if you're interested) but it would be good to get it supported

**Comment by jskeet** [comment]
@garethbudden: The Kubernetes API is only available with "compute credentials" (the default on GKE machines) if you have "Legacy authorisation" enabled in your cluster, which isn't the default or the recommended setup.

What we've got now definitely isn't where I'd like it to be, but I honestly don't know the best way forward at this stage :(

**Comment by amanda-tarafa** [comment]
I'm assigning this to myself as well so I remember to check the state of things internally before 3.0.

**Comment by amanda-tarafa** [comment]
I've asked internally for more information about legacy/new monitoring in Kubernetes. I will update here when we get the info and have come up with how we want to support this.

**Comment by amanda-tarafa** [comment]
Given our current plan of migrating GAX and Google Cloud .NET client libraries to gRPC C# 2.x (see googleapis/google-cloud-dotnet#3519) our plan regarding this issue is as follows:

- Keep GAX v2.x (current version) creating legacy types only, that is  "container" or "gke_container" (pre/post #346)
- Have GAX v3.x (first beta release probably next week 2020-02-17) create new types only, that is "k8s_container".
- We won't support conditional creation of legacy/new types, mainly because there doesn't seem to be a consistent/documented way to detect whether running on legacy/new. 
- In places in which we create monitored resources whith a given type, client code has the possibility to modify such types after creation, so client code is free to detect legacy/new and modify the resources' types accordingly. If we've missed a case in which this is not possible, please feel free to open a new issue describing the problem.

**Comment by amanda-tarafa** [comment]
As a follow up comment, the changes to support Stackdriver Kubernetes Engine Monitoring are a little more complex than just changing the type of the monitored resource. Still, code needing to support Legacy Stackdriver could still do so because all the information needed to build a Legacy GKE `Google.Api.MonitoredResource` can be found in `Google.Api.Gax.GkePlatformDetails`. An instance of `Google.Api.Gax.GkePlatformDetails` representing the platform the code is running in can be obtained by calling `Google.Api.Gax.Platfomr.Instance()`.
