### ISSUE TITLE
Investigate server-side streaming retry

### ISSUE THREAD

**Issue by jskeet** [googleapis/gax-dotnet#367]
Currently we *attempt* to retry server-side streaming, but it's unclear whether or not that works. We should validate.

**Comment by jskeet** [comment]
Just tested this with Firestore - I can get the headers without an issue, even if the call fails server-side.
It's possible that it *could* correctly detect "the server has gone away" or similar, but that's probably not terribly useful.

Options:

- Keep doing what we're doing even though it's useless
- Fail if there are retry settings
- Ignore retry settings

**Comment by jadekler** [comment]
Could you expand on this?

- Does "retry server side streaming" mean retry the RPC?
- Under which conditions do you want to retry? A specific error, or?
- Could you expand on "I can get the headers"? As in, the client can read the metadata the server sends when the client initiates an RPC? If so: why is this meaningful? Is there a reason it would not?
- In your email, it seems like a lot of the crux of the issue is around whether to wait for a response from the server or not. Is that true? Could you expand on that in this issue? And, if so, probably worth getting gRPC folks to weigh in, and to discuss why the server wouldn't return something like EOF or an error immediately.

**Comment by jskeet** [comment]
Responses for corresponding bullets:

- Yes, this is about retrying the RPC. Every method in our client libraries (unary or streaming) allows a `CallSettings` to be specified, which can include retry settings. There are default settings for each method. The question is what we should do if there are retry settings for server-side streaming RPCs.
- Which errors would trigger retries is part of the RetrySettings. For example, it might just be on a single status code.
- C# gRPC allows the response headers to be read before any of the streaming responses - and even if I make an API call that will definitely fail (e.g. sending an invalid argument) I'm able to read the response headers without seeing any failure. Our current code reads the response headers as a sort of proxy for success - I don't remember why we thought this would work, but it clearly *doesn't* detect errors, at least not reliably.
- We definitely don't want to wait for an actual streaming response. But if the server fails the call immediately, it would be nice to know that. I don't know whether that's even feasible in gRPC though. Will ask Jan for more info.

**Comment by jtattermusch** [comment]
I can confirm that just reading the response headers is not a reliable way to detect errors (it would work if the call fails "completely" to an extent where the server doesn't even manage to send the response headers and fails immediately, but it won't work in many other cases)

Unfortunately the server streaming call API in C# doesn't allow awaiting the status code being received only (without also reading the responses). There is a call.GetStatus() method that gives the status, but if the call hasn't finished yet, it throws InvalidOperationException.

In principle, exposing the call's status code without reading the responses is possible (the information is available internally as  https://github.com/grpc/grpc/blob/a02d6b9be81cbadb60eed88b3b44498ba27bcba9/src/csharp/Grpc.Core/Internal/AsyncCall.cs#L47), but it's not exposed in the public API.

Some more thoughts
- for streaming RPCs, there's no way you can find out about the resulting statuscode unless the server actually terminates the RPC (and that can happen long time and many responses after the RPC has started). In this case the problem is inherent - you won't know about the failure unless it actually happens.
- could you use an client-side interceptor that checks if the response stream has seen an error (which can happen at any time during the lifetime of the RPC) and if so, it retries the RPC as needed?

**Comment by jskeet** [comment]
Thanks for the detail Jan. I strongly suspect that we should just not retry any streaming APIs. If it's not the first response that fails, retrying could end up duplicating client-side handling. While we *could* retry only if we haven't seen any previous responses, I'm not sure that the benefit is worth the complexity.

**Comment by jtattermusch** [comment]
That sounds reasonable. Also according to https://youtu.be/Naonb2XD_2Q?t=1635, it is likely that for retrying streaming calls, you'll need "application-level retries" - so not really something you can handle in the client libraries as a general case (some kind of "retry" strategy might work for one API, but it's bad for another API).

**Comment by jskeet** [comment]
Right. So that does leave open the question about whether we should:

- Fail to generate if the default settings include a retry
- Throw an exception if the specified settings include a retry

**Comment by jtattermusch** [comment]
> Right. So that does leave open the question about whether we should:
> 
> * Fail to generate if the default settings include a retry
> * Throw an exception if user-specified settings include a retry

Both sounds reasonable to me, but I don't know the APIs well enough to be able to make the call.
