### ISSUE TITLE
Better check for Grpc.Net.Client compatibility?

### ISSUE THREAD

**Issue by AnashOommen** [googleapis/gax-dotnet#587]
https://github.com/googleapis/gax-dotnet/blob/main/Google.Api.Gax.Grpc/GrpcAdapter.cs#L119: 

* The library is now supported on netstandard2.1, .net5+ and net461+. 
* https://docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-6.0#net-grpc-client-requirements says that there's full support on .NET Core 3 and later.
* https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1#net-5-and-net-standard says that .netstandard 2.1 is supported in .NET and .NET Core 3.0, 3.1, 5.0, 6.0

So I think the `DetectDefaultGrpcTransportAdapterPreferringGrpcNetClient` method can be simplified as:

```c#
#if NETSTANDARD2_1
  return true;
#elif NET5_0_OR_GREATER
  return true;
#else
  return false;
#endif
```

**Comment by jskeet** [comment]
The problem with doing the check that way is that it means we wouldn't use Grpc.Net.Client *even when it's available*.

The aim of the current code is that when the Windows patches have all eventually rolled out so that .NET Framework support works, we'll use Grpc.Net.Client. We really want to reduce Grpc.Core usage as far as possible.

**Comment by jskeet** [comment]
@AnashOommen: Any feedback on my comment from a few weeks ago? It would be good to know whether you think we should still make changes.

**Comment by AnashOommen** [comment]
I think we can close this issue, since I think your approach is more manageable long term.
